from __future__ import annotations

from llmcheck.quality import clean_markdown_text, clean_markdown_with_report, final_acceptance_report, quality_errors
from llmcheck.pipeline import _issues_are_finalization_safe


def test_clean_markdown_text_normalizes_latex_unit_artifacts() -> None:
    text = "瓜蒌  $9\\mathrm{g}, 薤白 \\mathrm{g}$ ，半夏 $ \\mathrm{ } 12\\mathrm{g}$。体温 $40.1^{\\circ} \\mathrm{C}$ ."

    cleaned = clean_markdown_text(text)

    assert "9g" in cleaned
    assert "12g" in cleaned
    assert "40.1℃" in cleaned
    assert "g" in cleaned
    assert "\\mathrm" not in cleaned
    assert "\\circ" not in cleaned
    assert "$" not in cleaned


def test_clean_markdown_text_normalizes_latex_lab_values_and_short_breaks() -> None:
    text = (
        "TBIL $428\\mu \\mathrm{mol} /L ， $\\mathrm{A} / \\mathrm{G} = 1.3$ ，尿蛋白 +\\dots + ，Pt18.4秒。\n"
        "红细胞\n\n$4\\sim 6$\n\n"
        "暮夜神情安静，胸痛得减，至第五日热平，继而转予清\n宣泄化。\n"
    )

    cleaned = clean_markdown_text(text)

    assert "TBIL 428μmol/L" in cleaned
    assert "A/G=1.3" in cleaned
    assert "尿蛋白 +… +" in cleaned
    assert "红细胞4~6" in cleaned
    assert "继而转予清宣泄化" in cleaned
    assert "\\mathrm" not in cleaned
    assert "\\mu" not in cleaned
    assert "\\sim" not in cleaned
    assert "\\dots" not in cleaned
    assert "$" not in cleaned


def test_clean_markdown_text_merges_blank_separated_paragraph_fragments() -> None:
    text = (
        "本套丛书以每位医家独立成册，每册按医家小传、专病论治、诊余漫话、年谱四部分进行编写。其中，医家小传简要介绍医家的\n\n"
        "生平及成才之路；专病论治意在以病统论、以论统案、以案统话，便于临床学习与借鉴，诊余漫话则系读书体会\n\n"
        "札记，也可以是习医心得。\n"
    )

    report = clean_markdown_with_report(text)
    cleaned = str(report["text"])

    assert "医家的生平及成才之路" in cleaned
    assert "读书体会札记" in cleaned
    assert "医家的\n\n生平" not in cleaned
    assert "读书体会\n\n札记" not in cleaned
    assert any(change["rule_id"] == "paragraph.safe_line_join" for change in report["rule_changes"])


def test_clean_markdown_text_merges_blank_separated_chronology_fragments() -> None:
    text = (
        "1905～1912年江苏如皋马塘镇邓氏私塾读书\n\n"
        "1913～1916年 在家自学中医药1917～1920年 马塘大德生药号半工半读"
        "1921～1923年 受聘马塘济生会设案开诊1924～1946年马塘镇王家院自设诊所行医"
        "1947～1954年迁江苏省南通市寺德二号自设诊所行医。\n"
    )

    report = clean_markdown_with_report(text)
    cleaned = str(report["text"])

    assert "forced_line_breaks" in final_acceptance_report(text)["blocking_errors"]
    assert "- 1905～1912年江苏如皋马塘镇邓氏私塾读书" in cleaned
    assert "- 1913～1916年 在家自学中医药1917～1920年" in cleaned
    assert "forced_line_breaks" not in quality_errors(cleaned)
    assert any(change["rule_id"] == "structure.chronology_list_normalize" for change in report["rule_changes"])


def test_clean_markdown_text_merges_blank_separated_formula_fragments() -> None:
    text = (
        "生黄芪 60g 赤芍 10g 三七 3g （冲）蒲公英 20g\n\n"
        "紫草 10g 3付\n\n"
        "三诊 2004年10月14日。患者今日阴道出血量较前增多，处方如下：\n\n"
        "云茯苓12克 生熟地各9克 炒白术10克 路路通\n\n"
        "10克 公丁香2.5克 石楠叶9克 怀牛膝9克 7剂按：肝藏血主疏泄。\n\n"
        "熟地9克 当归9克 丹参9克 制香附9克 炒白术\n\n"
        "9克 怀牛膝 9 克 党参 12 克 制黄精 12 克 茯苓 9 克炙狗脊 12 克 陈皮 4.5 克 7 剂按：本案虽年龄未值七七，但因术后化疗，脾肾不足，气血大亏。\n"
    )

    cleaned = clean_markdown_text(text)

    assert "蒲公英 20g紫草 10g 3付三诊" in cleaned
    assert "路路通10克 公丁香" in cleaned
    assert "炒白术9克 怀牛膝" in cleaned
    assert "蒲公英 20g\n\n紫草" not in cleaned
    assert "路路通\n\n10克" not in cleaned
    assert "炒白术\n\n9克" not in cleaned


def test_clean_markdown_text_removes_trailing_archive_metadata_block() -> None:
    text = (
        "# 正文标题\n\n"
        "这里是正常医学正文，应该完整保留。\n\n"
        "Document generated by Anna's Archive around 2023-2024 as part of the DuXiu collection\n\n"
        "\"filename\": \"abc=\"\n\n"
        "\"filename_decoded\": \"\\u4e2d\\u56fd.zip\",\n\n"
        "\"pdg_main_pages_found\": 300,\n\n"
        "\"pdf_generation MISSING_pages\": false }\n"
    )

    report = clean_markdown_with_report(text)
    cleaned = str(report["text"])

    assert "# 正文标题" in cleaned
    assert "这里是正常医学正文" in cleaned
    assert "Document generated by Anna's Archive" not in cleaned
    assert "filename_decoded" not in cleaned
    assert "\\u4e2d" not in cleaned
    assert any(change["rule_id"] == "metadata.trailing_archive_block_remove" for change in report["rule_changes"])


def test_clean_markdown_text_normalizes_temperature_percent_ocr_artifacts() -> None:
    text = "患者高热，体温 38% ~ 40% 之间。服药后体温降至 37.0% 左右。体温 38℃ ~ 39% 已2天。检验阳性率 38% 不应改。\n"

    report = clean_markdown_with_report(text)
    cleaned = str(report["text"])

    assert "体温 38℃~40℃ 之间" in cleaned
    assert "体温降至 37.0℃ 左右" in cleaned
    assert "体温 38℃~39℃ 已2天" in cleaned
    assert "阳性率 38%" in cleaned
    assert any(change["rule_id"] == "ocr.temperature_percent_to_celsius" for change in report["rule_changes"])


def test_clean_markdown_text_keeps_temperature_outcome_percentages() -> None:
    text = "第1天体温降至正常的41例，占 38.3% ；第3天33例，占 30.8%。另患儿体温 39% 已2天。\n"

    cleaned = clean_markdown_text(text)

    assert "占 38.3%" in cleaned
    assert "占 30.8%" in cleaned
    assert "占 38.3℃" not in cleaned
    assert "体温 39℃ 已2天" in cleaned


def test_clean_markdown_text_normalizes_nested_latex_blood_pressure_units() -> None:
    text = "血压降至 {18.7}/{12.0}\\mathrm{{kPa}}\\left( {{140}/{90}\\mathrm{{mmHg}}}\\right) 。\n"

    cleaned = clean_markdown_text(text)

    assert "18.7/12.0kPa(140/90mmHg)" in cleaned
    assert "\\mathrm" not in cleaned
    assert "\\left" not in cleaned
    assert "\\right" not in cleaned
    assert "{" not in cleaned
    assert "}" not in cleaned


def test_clean_markdown_text_normalizes_latex_array_residue() -> None:
    text = "天癸（成熟） 促使冲任（相通） → 生殖之精成熟 → 胞宫 \\left\\{ array{l}月经来潮\\\\ 能有子 array .\n"

    cleaned = clean_markdown_text(text)

    assert "胞宫 月经来潮；能有子" in cleaned
    assert "\\left" not in cleaned
    assert "array" not in cleaned
    assert "\\\\" not in cleaned


def test_clean_markdown_text_normalizes_latex_aligned_flowchart_residue() -> None:
    text = (
        "风中 \\left\\{aligned经络——口眼不正\\\\ 身肢——偏枯不遂\\\\ 脏——内闭\\\\ "
        "腑——便溺不利\\\\ 脏腑——内闭外脱aligned.\n"
        "伤脾 \\left\\{ array{l l} 伤阴——口干 \\\\ 伤阳——便溏 array .\n"
    )

    cleaned = clean_markdown_text(text)

    assert "风中 经络——口眼不正；身肢——偏枯不遂；脏——内闭；腑——便溺不利；脏腑——内闭外脱" in cleaned
    assert "伤脾 伤阴——口干；伤阳——便溏" in cleaned
    assert "\\left" not in cleaned
    assert "aligned" not in cleaned
    assert "array" not in cleaned
    assert "latex_artifacts" not in final_acceptance_report(cleaned)["blocking_errors"]


def test_clean_markdown_text_normalizes_latex_mid_in_tables() -> None:
    text = "| 肺(金) | 补土{太渊 \\mid 太白} | 泻水{尺泽 \\mid 阴谷} |\n"

    cleaned = clean_markdown_text(text)

    assert "补土{太渊 | 太白}" in cleaned or "补土{太渊|太白}" in cleaned
    assert "\\mid" not in cleaned
    assert "latex_artifacts" not in final_acceptance_report(cleaned)["blocking_errors"]


def test_clean_markdown_text_normalizes_latex_bigcirc_bullets() -> None:
    text = "\\bigcirc 咳血，针灸肺俞。\\bigcirc 咯血，针郄门。\n"

    cleaned = clean_markdown_text(text)

    assert "○ 咳血" in cleaned
    assert "○ 咯血" in cleaned
    assert "\\bigcirc" not in cleaned


def test_clean_markdown_text_normalizes_latex_star_bullets() -> None:
    text = "\\star （一）宜肺平喘，清热解毒；\n"

    cleaned = clean_markdown_text(text)

    assert "★ （一）宜肺平喘" in cleaned
    assert "\\star" not in cleaned


def test_clean_markdown_text_normalizes_latex_triangle_bullets() -> None:
    text = "\\triangle 有些治学不严谨的临床教师。\n"

    cleaned = clean_markdown_text(text)

    assert "△ 有些治学不严谨" in cleaned
    assert "\\triangle" not in cleaned


def test_clean_markdown_text_normalizes_latex_wedge_geometry_marker() -> None:
    text = "再以纸绳作 \\wedge 字形，中间置鼻中膈之下，两端齐口角。"
    cleaned = clean_markdown_text(text)
    assert "\\wedge" not in cleaned
    assert "∧" in cleaned
    assert "latex_artifacts" not in final_acceptance_report(cleaned)["blocking_errors"]


def test_clean_markdown_text_normalizes_latex_odot_and_theta_symbols() -> None:
    text = "右眼 +1.00S \\odot + 0.25C× 90^° = 0.4。\n\n\\Theta 理中汤（《伤寒论》）\n"

    cleaned = clean_markdown_text(text)

    assert "+1.00S ⊙ + 0.25C× 90°" in cleaned
    assert "Θ 理中汤" in cleaned
    assert "\\odot" not in cleaned
    assert "\\Theta" not in cleaned


def test_clean_markdown_text_normalizes_latex_clubsuit_footnote_marker() -> None:
    text = "| 兼有虚证 | 气虚 | 人参*、灵芝* |\n\n注 \\clubsuit 者本身还有降脂作用\n"

    cleaned = clean_markdown_text(text)

    assert "注 * 者本身还有降脂作用" in cleaned
    assert "\\clubsuit" not in cleaned


def test_clean_markdown_text_normalizes_latex_angle_comparison_symbols() -> None:
    text = "男性血红蛋白（Hb） \\langle 110g/L；女性 \\langle 100g/L；区间 \\langle x \\rangle。\n"

    cleaned = clean_markdown_text(text)

    assert "Hb） < 110g/L" in cleaned
    assert "女性 < 100g/L" in cleaned
    assert "< x >" in cleaned
    assert "\\langle" not in cleaned
    assert "\\rangle" not in cleaned


def test_clean_markdown_text_normalizes_latex_slanted_comparison_symbols() -> None:
    text = "大量蛋白尿（ \\geqslant 3.5g/ 24h ）、低蛋白血症（ \\leqslant 30g/L ）。\n"

    cleaned = clean_markdown_text(text)

    assert "≥ 3.5g/ 24h" in cleaned
    assert "≤ 30g/L" in cleaned
    assert "\\geqslant" not in cleaned
    assert "\\leqslant" not in cleaned


def test_clean_markdown_text_normalizes_latex_phi_symbol() -> None:
    text = "显著增强腹腔 M\\Phi 吞噬功能。\n"

    cleaned = clean_markdown_text(text)

    assert "MΦ 吞噬功能" in cleaned
    assert "\\Phi" not in cleaned


def test_clean_markdown_text_normalizes_bare_mathrm_dosage_residue() -> None:
    text = "甘中黄 \\mathrm3g 2剂煎服。\n"

    cleaned = clean_markdown_text(text)

    assert "甘中黄 3g 2剂煎服" in cleaned
    assert "\\mathrm" not in cleaned


def test_clean_markdown_text_normalizes_latex_dosage_symbol_residue() -> None:
    text = "葛 \\mathbf9g，甘草 \\mathbf6g，炒补骨脂 \\varrho_g。腹胀痛加枳实 9\\pi 以行气止痛。川贝母 \\dot9g。\n"

    cleaned = clean_markdown_text(text)

    assert "葛 9g" in cleaned
    assert "甘草 6g" in cleaned
    assert "炒补骨脂 9g" in cleaned
    assert "枳实 9g 以行气止痛" in cleaned
    assert "川贝母 9g" in cleaned
    assert "\\mathbf" not in cleaned
    assert "\\varrho" not in cleaned
    assert "\\pi" not in cleaned
    assert "\\dot" not in cleaned


def test_clean_markdown_text_normalizes_latex_dosage_before_joined_chinese_text() -> None:
    text = "葛 \\mathbf9g大黄（兑） 9g。炒补骨脂 \\varrho_g本方温补脾肾两阳。\n"

    cleaned = clean_markdown_text(text)

    assert "葛 9g大黄（兑） 9g" in cleaned
    assert "炒补骨脂 9g本方温补脾肾两阳" in cleaned
    assert "\\mathbf" not in cleaned
    assert "\\varrho" not in cleaned


def test_clean_markdown_text_normalizes_latex_zeta_dosage_residue() -> None:
    text = "金钱草 15~30g，芍药 \\zeta ~ 30g，木香 6~20g。\n"

    cleaned = clean_markdown_text(text)

    assert "芍药 6~30g" in cleaned
    assert "\\zeta" not in cleaned


def test_clean_markdown_text_normalizes_latex_half_needle_gauge() -> None:
    text = "配带 4\\frac12 号针头，在肛门周围皮内做点状注射。\n"

    cleaned = clean_markdown_text(text)

    assert "4.5 号针头" in cleaned
    assert "\\frac" not in cleaned


def test_clean_markdown_text_normalizes_menstrual_fraction_shorthand() -> None:
    text = (
        "月经 14\\frac5 - 720 - 25 ，量不多。\n"
        "月经14 \\frac5~618~20 ，量多。\n"
        "月经 13\\frac540~50 ，量中等。\n"
        "月经 13\\frac7~1025 ，量较多。\n"
        "月经 13\\frac130 ，量少。\n"
        "月经 13\\frac4 - 625 - 30 天，量中等。\n"
        "月经 14\\frac3 - 530 - 35 经量中等。\n"
        "周期 \\frac3 - 620 - 21 天，量不多。\n"
        "周期 \\frac4 - 518 - 21 天，量多。\n"
        "月经史 \\frac4 - 640 - 50 天，量中等。\n"
        "月经 \\frac540 - 60 天，量少。\n"
        "周期 \\frac328 - 30 天，量可。\n"
        "周期 \\frac14 - 1725 - 28 天，量中等。\n"
    )

    cleaned = clean_markdown_text(text)

    assert "月经 14 5~7/20~25" in cleaned
    assert "月经14 5~6/18~20" in cleaned
    assert "月经 13 5/40~50" in cleaned
    assert "月经 13 7~10/25" in cleaned
    assert "月经 13 1/30" in cleaned
    assert "月经 13 4~6/25~30 天" in cleaned
    assert "月经 14 3~5/30~35 经量中等" in cleaned
    assert "周期 3~6/20~21 天" in cleaned
    assert "周期 4~5/18~21 天" in cleaned
    assert "月经史 4~6/40~50 天" in cleaned
    assert "月经 5/40~60 天" in cleaned
    assert "周期 3/28~30 天" in cleaned
    assert "周期 14~17/25~28 天" in cleaned
    assert "\\frac" not in cleaned


def test_clean_markdown_text_normalizes_latex_breadcrumb_separator() -> None:
    text = "所属分类：图书 \\gg 医学 \\gg 中医学 \\gg 中医临床\n"

    cleaned = clean_markdown_text(text)

    assert "图书 ≫ 医学 ≫ 中医学 ≫ 中医临床" in cleaned
    assert "\\gg" not in cleaned


def test_clean_markdown_text_normalizes_prime_dosage_range_residue() -> None:
    text = "麦冬 10^\\prime ~ 12 克、鳖甲 15~30 克。\n"

    cleaned = clean_markdown_text(text)

    assert "麦冬 10~12 克" in cleaned
    assert "\\prime" not in cleaned


def test_clean_markdown_text_normalizes_equiv_symbol() -> None:
    text = "浮小而无力 = 濡--濡甚 \\equiv 微\n"

    cleaned = clean_markdown_text(text)

    assert "濡--濡甚 ≡ 微" in cleaned
    assert "\\equiv" not in cleaned


def test_clean_markdown_text_removes_embedded_foreign_theorem_ocr_noise() -> None:
    text = (
        "升清降浊，关键在于掌握分寸。药"
        "Theorem 1.2. (Theorem of [10, Theorem 1.1]) Let F be a finite field and let F(x) be the set of all elements of F such that"
        "黄，脉象细滑。此乃胃中有热。\n"
    )

    report = clean_markdown_with_report(text)
    cleaned = str(report["text"])

    assert "Theorem 1.2" not in cleaned
    assert "finite field" not in cleaned
    assert "药黄，脉象细滑" in cleaned
    assert "\\in" not in cleaned
    assert any(change["rule_id"] == "ocr.embedded_foreign_math_noise_remove" for change in report["rule_changes"])


def test_clean_markdown_text_removes_embedded_short_math_ocr_noise() -> None:
    text = "2000年 《养生保健箴言》撰写成。   \\therefore m - 1 \\neq 0 ;   # 附录\n"

    report = clean_markdown_with_report(text)
    cleaned = str(report["text"])

    assert "\\therefore" not in cleaned
    assert "\\neq" not in cleaned
    assert "m - 1" not in cleaned
    assert "2000年 《养生保健箴言》撰写成。" in cleaned
    assert "# 附录" in cleaned
    assert any(change["rule_id"] == "ocr.embedded_foreign_math_noise_remove" for change in report["rule_changes"])


def test_clean_markdown_text_normalizes_menstrual_history_frac_residue() -> None:
    text = "月经史：14\\frac3~428~30 天。另载：14 \\frac3~428~30 天。\n"

    cleaned = clean_markdown_text(text)

    assert "14 3~4/28~30 天" in cleaned
    assert "14\\frac" not in cleaned
    assert "\\frac" not in cleaned


def test_final_acceptance_report_blocks_latex_unit_residue() -> None:
    report = final_acceptance_report("# 标题\n\n体温 $40.1^{\\circ} \\mathrm{C}$，瓜蒌 $9\\mathrm{g}$。\n")

    assert report["accepted"] is False
    assert "latex_artifacts" in report["blocking_errors"]


def test_clean_markdown_text_normalizes_latex_square_note_markers() -> None:
    text = "# 标题\n\n太阳中风 \\square^(1) ，恶风 \\square^③ ，桂枝汤主之。\n"

    cleaned = clean_markdown_text(text)

    assert "(1)" in cleaned
    assert "③" in cleaned
    assert "\\square" not in cleaned
    assert "latex_artifacts" not in final_acceptance_report(cleaned)["blocking_errors"]


def test_ocr_noise_acceptance_issues_can_enter_finalization_gate() -> None:
    assert _issues_are_finalization_safe([{"category": "ocr_noise"}]) is True
    assert _issues_are_finalization_safe([{"category": "missing_text"}]) is False
