from __future__ import annotations

import hashlib
import re
from typing import Any

from llmcheck.rules import normalize_write_mode, rule_definition


BAD_CONTROL_RE = re.compile(r"[\x00-\x08\x0b\x0e-\x1f\x7f]")
MOJIBAKE_PATTERNS = ("锟斤拷", "Ã", "Â", "â€™", "â€œ", "â€�")
ZERO_WIDTH_RE = re.compile(r"[​‌‍﻿]")
MINERU_FLOWCHART_DETAILS_RE = re.compile(
    r"\n*<details>\s*<summary>\s*flowchart\s*</summary>(?P<body>.*?)</details>\s*",
    re.IGNORECASE | re.DOTALL,
)
MINERU_NOISE_DETAILS_RE = re.compile(
    r"\n*<details>\s*<summary>\s*(?:line|text_image|flowchart|natural_image|radar)\s*</summary>.*?</details>\s*",
    re.IGNORECASE | re.DOTALL,
)
TRAILING_ARCHIVE_METADATA_RE = re.compile(
    r"\n{1,3}Document generated by Anna's Archive\b(?P<body>.*?)(?:\"filename_decoded\"|\"pdg_main_pages_found\"|\"pdf_generation MISSING_pages\").*\Z",
    re.DOTALL,
)
DEFAULT_STRUCTURE_LABELS = (
    "头部：",
    "面部：",
    "项部：",
    "颈部：",
    "肩部：",
    "背部：",
    "胸部：",
    "腹部：",
    "腰部：",
    "肘部：",
    "腕部：",
    "手部：",
    "髀部：",
    "髋部：",
    "膝部：",
    "踝部：",
    "足部：",
    "Shoulder:",
    "Elbow:",
    "Wrist:",
)
DEFAULT_TABLE_HEADERS: tuple[tuple[str, ...], ...] = (
    ("分类", "药名", "功效", "主治", "用量"),
    ("类别", "药名", "功效", "主治", "用量"),
    ("方名", "出处", "组成", "功效", "主治", "用法"),
    ("方名", "来源", "药物组成", "功效", "主治", "制用法"),
)
LOCAL_REPAIR_CATEGORIES = {"layout", "ocr_noise", "punctuation", "missing_text"}


def clean_markdown_text(
    text: str,
    *,
    structure_labels: tuple[str, ...] | None = None,
    table_headers: tuple[tuple[str, ...], ...] | None = None,
) -> str:
    return str(clean_markdown_with_report(text, structure_labels=structure_labels, table_headers=table_headers)["text"])


def clean_markdown_with_report(
    text: str,
    *,
    structure_labels: tuple[str, ...] | None = None,
    table_headers: tuple[tuple[str, ...], ...] | None = None,
) -> dict[str, object]:
    cleaned = text
    rule_changes: list[dict[str, object]] = []

    cleaned = _apply_cleaning_rule(
        rule_changes,
        cleaned,
        rule_id="artifact.zero_width_remove",
        risk_level="low",
        transform=lambda value: ZERO_WIDTH_RE.sub("", value),
        match_count=len(ZERO_WIDTH_RE.findall(cleaned)),
    )
    cleaned = _apply_cleaning_rule(
        rule_changes,
        cleaned,
        rule_id="artifact.replacement_char_remove",
        risk_level="medium",
        transform=lambda value: value.replace("\ufffd", ""),
        match_count=cleaned.count("\ufffd"),
    )
    cleaned = _apply_cleaning_rule(
        rule_changes,
        cleaned,
        rule_id="artifact.form_feed_to_newline",
        risk_level="low",
        transform=lambda value: value.replace("\x0c", "\n"),
        match_count=cleaned.count("\x0c"),
    )
    cleaned = _apply_cleaning_rule(
        rule_changes,
        cleaned,
        rule_id="artifact.bad_control_remove",
        risk_level="low",
        transform=lambda value: BAD_CONTROL_RE.sub("", value),
        match_count=len(BAD_CONTROL_RE.findall(cleaned)),
    )
    cleaned = _apply_cleaning_rule(
        rule_changes,
        cleaned,
        rule_id="line_endings.normalize",
        risk_level="low",
        transform=lambda value: re.sub(r"\r\n?", "\n", value),
        match_count=len(re.findall(r"\r\n?", cleaned)),
    )
    cleaned = _apply_cleaning_rule(
        rule_changes,
        cleaned,
        rule_id="metadata.trailing_archive_block_remove",
        risk_level="low",
        transform=_remove_trailing_archive_metadata_artifacts,
        match_count=len(TRAILING_ARCHIVE_METADATA_RE.findall(cleaned)),
    )
    cleaned = _apply_cleaning_rule(
        rule_changes,
        cleaned,
        rule_id="ocr.embedded_foreign_math_noise_remove",
        risk_level="medium",
        transform=_remove_embedded_foreign_math_noise_artifacts,
        match_count=len(re.findall(r"Theorem\s+\d+(?:\.\d+)*\.", cleaned)),
    )
    cleaned = _apply_cleaning_rule(
        rule_changes,
        cleaned,
        rule_id="latex.unit_math_to_text",
        risk_level="low",
        transform=_normalize_latex_unit_artifacts,
        match_count=len(
            re.findall(
                r"(?:\$|\\(?:mathrm|mathbf|frac|circ|mu|sim|degree|times|cdot|odot|langle|rangle|leq|geq|leqslant|geqslant|neq|ne|gg|equiv|varrho|pi|clubsuit|star|zeta|triangle|Theta|square))",
                cleaned,
            )
        ),
    )
    cleaned = _apply_cleaning_rule(
        rule_changes,
        cleaned,
        rule_id="ocr.temperature_percent_to_celsius",
        risk_level="medium",
        transform=_normalize_temperature_percent_artifacts,
        match_count=len(re.findall(r"(?:体温|发热|高热|高烧|热势)[^。！？!?；;\n]{0,160}\d{2}(?:\.\d+)?\s*%", cleaned)),
    )
    cleaned = _apply_cleaning_rule(
        rule_changes,
        cleaned,
        rule_id="mineru.flowchart_transcribe",
        risk_level="medium",
        transform=_transcribe_table_flowchart_details,
        match_count=len(MINERU_FLOWCHART_DETAILS_RE.findall(cleaned)),
    )
    cleaned = _apply_cleaning_rule(
        rule_changes,
        cleaned,
        rule_id="mineru.noise_details_remove",
        risk_level="low",
        transform=lambda value: MINERU_NOISE_DETAILS_RE.sub("\n\n", value),
        match_count=len(MINERU_NOISE_DETAILS_RE.findall(cleaned)),
    )
    cleaned = _apply_cleaning_rule(
        rule_changes,
        cleaned,
        rule_id="html.table_tags_to_markdown",
        risk_level="medium",
        transform=_html_table_tags_to_markdown,
        match_count=len(re.findall(r"</?(?:table|thead|tbody|tfoot|tr|td|th)\b", cleaned, flags=re.IGNORECASE)),
    )
    cleaned = _apply_cleaning_rule(
        rule_changes,
        cleaned,
        rule_id="structure.local_glue_split",
        risk_level="medium",
        transform=lambda value: _split_local_structure_glue(value, structure_labels=structure_labels),
    )
    lines = [line.rstrip() for line in cleaned.split("\n")]
    table_lines = _normalize_markdown_tables(lines, table_headers=table_headers)
    cleaned = _record_line_rule(
        rule_changes,
        before="\n".join(lines),
        after="\n".join(table_lines),
        rule_id="markdown.table_normalize",
        risk_level="medium",
    )
    chronology_lines = _normalize_chronology_list_lines(table_lines)
    cleaned = _record_line_rule(
        rule_changes,
        before="\n".join(table_lines),
        after="\n".join(chronology_lines),
        rule_id="structure.chronology_list_normalize",
        risk_level="medium",
    )
    merged_lines = _merge_soft_wrapped_lines(chronology_lines, structure_labels=structure_labels)
    cleaned = _record_line_rule(
        rule_changes,
        before="\n".join(table_lines),
        after="\n".join(merged_lines),
        rule_id="paragraph.safe_line_join",
        risk_level="medium",
    )
    stripped = re.sub(r"\n{4,}", "\n\n\n", cleaned).strip()
    cleaned = _record_line_rule(
        rule_changes,
        before=cleaned,
        after=stripped + "\n" if stripped else "",
        rule_id="markdown.blank_lines_and_trailing_newline",
        risk_level="low",
    )
    return {
        "status": "cleaned",
        "text": cleaned,
        "input_sha256": _text_sha256(text),
        "output_sha256": _text_sha256(cleaned),
        "rule_changes": rule_changes,
    }


def safe_stem(value: str) -> str:
    stem = re.sub(r"[\\/:*?\"<>|\s]+", "_", value).strip("._")
    return stem or "document"


def repair_acceptance_locally(text: str, acceptance: dict[str, Any]) -> dict[str, Any]:
    issues = _acceptance_blocking_issues(acceptance)
    targeted = [issue for issue in issues if str(issue.get("category") or "") in LOCAL_REPAIR_CATEGORIES]
    if not targeted or acceptance.get("accepted") is True:
        return {"status": "skipped", "repaired": False, "issue_count": len(issues), "summary": "没有可本地定点修复的验收问题"}

    repaired_text = clean_markdown_text(text)
    changes: list[dict[str, str]] = []
    for issue in targeted:
        excerpt = str(issue.get("excerpt") or "").strip()
        if not excerpt:
            continue
        repaired_excerpt = clean_markdown_text(excerpt).strip()
        if repaired_excerpt and repaired_excerpt != excerpt and excerpt in repaired_text:
            repaired_text = repaired_text.replace(excerpt, repaired_excerpt, 1)
            changes.append(
                {
                    "location_hint": str(issue.get("location_hint") or ""),
                    "category": str(issue.get("category") or ""),
                    "before": excerpt[:160],
                    "after": repaired_excerpt[:160],
                }
            )

    repaired_text = clean_markdown_text(repaired_text)
    if repaired_text == text:
        return {
            "status": "not_repaired",
            "repaired": False,
            "issue_count": len(targeted),
            "summary": "本地规则未产生文本变化",
        }
    return {
        "status": "repaired",
        "repaired": True,
        "issue_count": len(targeted),
        "changes": changes,
        "repaired_text": repaired_text,
        "summary": f"已按验收失败项执行 {len(targeted)} 个本地定点修复规则",
    }


def _apply_cleaning_rule(
    rule_changes: list[dict[str, object]],
    value: str,
    *,
    rule_id: str,
    risk_level: str,
    transform: Any,
    match_count: int | None = None,
    write_mode: str = "auto_apply",
) -> str:
    updated = str(transform(value))
    if updated != value:
        rule_changes.append(_rule_change(rule_id, value, updated, risk_level=risk_level, write_mode=write_mode, match_count=match_count))
    return updated


def _record_line_rule(
    rule_changes: list[dict[str, object]],
    *,
    before: str,
    after: str,
    rule_id: str,
    risk_level: str,
    write_mode: str = "auto",
) -> str:
    if after != before:
        rule_changes.append(_rule_change(rule_id, before, after, risk_level=risk_level, write_mode=write_mode))
    return after


def _rule_change(
    rule_id: str,
    before: str,
    after: str,
    *,
    risk_level: str,
    write_mode: str,
    match_count: int | None = None,
) -> dict[str, object]:
    definition = rule_definition(rule_id)
    normalized_write_mode = normalize_write_mode(write_mode or (definition.write_mode if definition else "auto_apply"))
    normalized_risk_level = risk_level or (definition.risk_level if definition else "medium")
    return {
        "rule_id": rule_id,
        "description": definition.description if definition else "",
        "risk_level": normalized_risk_level,
        "write_mode": normalized_write_mode,
        "match_count": max(1, int(match_count or 1)),
        "input_sha256": _text_sha256(before),
        "output_sha256": _text_sha256(after),
        "examples": [{"before": _preview_change_text(before), "after": _preview_change_text(after)}],
    }


def _preview_change_text(value: str, *, limit: int = 160) -> str:
    compact = re.sub(r"\s+", " ", value).strip()
    return compact[:limit]


def _normalize_latex_unit_artifacts(text: str) -> str:
    unit_names = r"g|mg|kg|ug|μg|ml|mL|L|mm|cm|m|min|s|h|kPa|mol|U"
    cleaned = re.sub(
        r"\$?\s*(?P<number>\d+(?:\.\d+)?)\s*(?:\^\s*\{\s*\\circ\s*\}|\^\s*\\circ|\\circ)\s*(?:\\mathrm\s*\{\s*C\s*\}|C)\s*\$?",
        lambda match: f" {match.group('number')}℃",
        text,
    )
    cleaned = re.sub(
        r"(?<!\d)(?P<age>\d{1,2})\s*\\frac\s*(?P<days_start>\d{1,2})\s*~\s*(?P<days_end>\d{1,2})(?P<cycle_start>\d{2})\s*~\s*(?P<cycle_end>\d{2})\s*(?P<unit>天)?",
        lambda match: (
            f"{match.group('age')} {match.group('days_start')}~{match.group('days_end')}/"
            f"{match.group('cycle_start')}~{match.group('cycle_end')}"
            f"{(' ' + match.group('unit')) if match.group('unit') else ''}"
        ),
        cleaned,
    )
    cleaned = re.sub(
        r"(?<!\d)(?P<age>\d{1,2})\s*\\frac\s*(?P<days_start>\d{1,2})\s*[-~]\s*(?P<days_end>\d{1,2})\s*(?P<cycle_start>\d{2})\s*[-~]\s*(?P<cycle_end>\d{2})(?:\s*(?P<unit>天))?(?=\s*(?:[，,。；;]|经量|量))",
        lambda match: (
            f"{match.group('age')} {match.group('days_start')}~{match.group('days_end')}/"
            f"{match.group('cycle_start')}~{match.group('cycle_end')}"
            f"{(' ' + match.group('unit')) if match.group('unit') else ''}"
        ),
        cleaned,
    )
    cleaned = re.sub(
        r"(?<!\d)(?P<age>\d{1,2})\s*\\frac\s*(?P<days_start>\d{1,2})\s*[-~]\s*(?P<days_end>\d{1,2})\s*(?P<cycle>\d{2})(?:\s*(?P<unit>天))?(?=\s*(?:[，,。；;]|经量|量))",
        lambda match: (
            f"{match.group('age')} {match.group('days_start')}~{match.group('days_end')}/{match.group('cycle')}"
            f"{(' ' + match.group('unit')) if match.group('unit') else ''}"
        ),
        cleaned,
    )
    cleaned = re.sub(
        r"(?<!\d)(?P<age>\d{1,2})\s*\\frac\s*(?P<days>\d{1,2})\s*(?P<cycle_start>\d{2})\s*[-~]\s*(?P<cycle_end>\d{2})(?:\s*(?P<unit>天))?(?=\s*(?:[，,。；;]|经量|量))",
        lambda match: (
            f"{match.group('age')} {match.group('days')}/{match.group('cycle_start')}~{match.group('cycle_end')}"
            f"{(' ' + match.group('unit')) if match.group('unit') else ''}"
        ),
        cleaned,
    )
    cleaned = re.sub(
        r"(?<!\d)(?P<age>\d{1,2})\s*\\frac\s*(?P<days>\d{1,2})\s*(?P<cycle>\d{2})(?:\s*(?P<unit>天))?(?=\s*(?:[，,。；;]|经量|量))",
        lambda match: f"{match.group('age')} {match.group('days')}/{match.group('cycle')}{(' ' + match.group('unit')) if match.group('unit') else ''}",
        cleaned,
    )
    cleaned = re.sub(
        r"\\frac\s*(?P<days_start>\d{1,2})\s*[-~]\s*(?P<days_end>\d{1,2})\s*(?P<cycle_start>\d{2})\s*[-~]\s*(?P<cycle_end>\d{2})(?:\s*(?P<unit>天))?(?=\s*(?:[，,。；;）)]|经量|量))",
        lambda match: (
            f"{match.group('days_start')}~{match.group('days_end')}/"
            f"{match.group('cycle_start')}~{match.group('cycle_end')}"
            f"{(' ' + match.group('unit')) if match.group('unit') else ''}"
        ),
        cleaned,
    )
    cleaned = re.sub(
        r"\\frac\s*(?P<days_start>\d{1,2})\s*[-~]\s*(?P<days_end>\d{1,2})\s*(?P<cycle>\d{2})(?:\s*(?P<unit>天))?(?=\s*(?:[，,。；;）)]|经量|量))",
        lambda match: (
            f"{match.group('days_start')}~{match.group('days_end')}/{match.group('cycle')}"
            f"{(' ' + match.group('unit')) if match.group('unit') else ''}"
        ),
        cleaned,
    )
    cleaned = re.sub(
        r"\\frac\s*(?P<days>\d{1,2})\s*(?P<cycle_start>\d{2})\s*[-~]\s*(?P<cycle_end>\d{2})(?:\s*(?P<unit>天))?(?=\s*(?:[，,。；;）)]|经量|量))",
        lambda match: (
            f"{match.group('days')}/{match.group('cycle_start')}~{match.group('cycle_end')}"
            f"{(' ' + match.group('unit')) if match.group('unit') else ''}"
        ),
        cleaned,
    )
    cleaned = re.sub(
        r"\\frac\s*(?P<days>\d{1,2})\s*(?P<cycle>\d{2})(?:\s*(?P<unit>天))?(?=\s*(?:[，,。；;）)]|经量|量))",
        lambda match: f"{match.group('days')}/{match.group('cycle')}{(' ' + match.group('unit')) if match.group('unit') else ''}",
        cleaned,
    )
    cleaned = re.sub(
        r"\\left\\\{\s*array\{[A-Za-z]+\}\s*(?P<body>[^\\\n]{1,120}(?:\\\\[^\\\n]{1,120}){1,8})\s*array\s*\.?",
        lambda match: re.sub(r"\s*\\\\\s*", "；", match.group("body")).strip(),
        cleaned,
    )
    cleaned = re.sub(r"(?<=\d)\s*\^\s*\\prime\s*(?=\s*~\s*\d)", "", cleaned)
    cleaned = re.sub(r"(?<=\d)\s*\^\s*°", "°", cleaned)
    cleaned = re.sub(r"\$?\s*\\mathrm\s*\{\s*\}\s*\$?", " ", cleaned)
    cleaned = re.sub(r"(?P<number>\d+)\\frac\s*1\s*2(?=\s*号(?:针头)?)", r"\g<number>.5", cleaned)
    dosage_unit_tail = r"(?=\s*(?:[㐀-鿿，,。；;、)）]|$))"
    cleaned = re.sub(
        rf"\\(?:mathrm|mathbf|mathsf|mathit|mathcal|mathbb)\s*(?=\d+(?:\.\d+)?(?:{unit_names}){dosage_unit_tail})",
        "",
        cleaned,
    )
    cleaned = re.sub(r"注\s*\\clubsuit\s*者", "注 * 者", cleaned)
    cleaned = re.sub(rf"\\varrho\s*_\s*g{dosage_unit_tail}", "9g", cleaned)
    cleaned = re.sub(r"(?<=\d)\\pi\b(?=\s*(?:以|[，,；;。]|$))", "g", cleaned)
    cleaned = re.sub(rf"\\zeta\s*~\s*(?=\d+(?:\.\d+)?\s*(?:{unit_names})\b)", "6~", cleaned)
    cleaned = re.sub(rf"\\dot\s*(?=\d+(?:\.\d+)?\s*(?:{unit_names})\b)", "", cleaned)
    latex_symbols = {
        "degreeC": "℃",
        "degree": "°",
        "circ": "°",
        "times": "×",
        "cdot": "·",
        "odot": "⊙",
        "pm": "±",
        "mu": "μ",
        "alpha": "α",
        "beta": "β",
        "gamma": "γ",
        "delta": "δ",
        "Delta": "Δ",
        "phi": "φ",
        "Phi": "Φ",
        "Theta": "Θ",
        "dots": "…",
        "ldots": "…",
        "bigcirc": "○",
        "square": "□",
        "clubsuit": "♣",
        "star": "★",
        "triangle": "△",
        "langle": "<",
        "rangle": ">",
        "sim": "~",
        "rightarrow": "→",
        "to": "→",
        "leq": "≤",
        "geq": "≥",
        "leqslant": "≤",
        "geqslant": "≥",
        "neq": "≠",
        "ne": "≠",
        "gg": "≫",
        "equiv": "≡",
    }
    for command, replacement in latex_symbols.items():
        cleaned = re.sub(rf"\\{command}(?![A-Za-z])", replacement, cleaned)
    cleaned = re.sub(r"□\s*\^\s*\(?\s*([0-9]+)\s*\)?", r"(\1)", cleaned)
    cleaned = re.sub(r"□\s*\^\s*([①-⑳ⅠⅡⅢⅣⅤⅥⅦⅧⅨⅩ])", r"\1", cleaned)
    cleaned = cleaned.replace(r"\%", "%")
    cleaned = re.sub(
        rf"\$?\s*(?P<number>\d+(?:\.\d+)?)\s*\\mathrm\s*\{{\s*(?P<unit>{unit_names})\s*\}}\s*\$?",
        lambda match: f" {match.group('number')}{match.group('unit')}",
        cleaned,
    )
    cleaned = re.sub(
        rf"\$?\s*\\mathrm\s*\{{\s*(?P<unit>{unit_names}|C)\s*\}}\s*\$?",
        lambda match: match.group("unit"),
        cleaned,
    )
    cleaned = re.sub(r"\\mathrm\s*(?=\d+(?:\.\d+)?(?:g|mg|kg|ug|μg|ml|mL|L|mm|cm|m|min|s|h|kPa)\b)", "", cleaned)
    cleaned = re.sub(r"\\mathrm\s*\{\{\s*([^{}\n]{1,80})\s*\}\}", r"\1", cleaned)
    cleaned = re.sub(r"\\(?:left|right)\s*([()\[\]{}|.])", r"\1", cleaned)
    cleaned = re.sub(r"\{\s*([^{}\n]{1,32})\s*\}\s*/\s*\{\s*([^{}\n]{1,32})\s*\}", r"\1/\2", cleaned)
    cleaned = re.sub(r"\{\s*([0-9][0-9./~×+\- ]{0,80}(?:kPa|mmHg|mg|g|ml|mL|L|℃)?)\s*\}", r"\1", cleaned)
    cleaned = re.sub(r"\(\s+(?=\d)", "(", cleaned)
    wrapper_commands = r"mathrm|mathbf|mathsf|text|operatorname|mathit|mathcal|mathbb"
    previous = None
    while previous != cleaned:
        previous = cleaned
        cleaned = re.sub(rf"\\(?:{wrapper_commands})\s*\{{\s*([^{{}}\n]{{1,160}})\s*\}}", r"\1", cleaned)
    cleaned = re.sub(r"\^\s*\{\s*([^{}\n]{1,32})\s*\}", r"^\1", cleaned)
    cleaned = re.sub(r"_\s*\{\s*([^{}\n]{1,32})\s*\}", r"_\1", cleaned)
    cleaned = re.sub(r"\$\s*([^$\n]{1,120})\s*\$", r"\1", cleaned)
    cleaned = cleaned.replace("$", "")
    cleaned = re.sub(r"(?<=\d)\s*~\s*(?=\d)", "~", cleaned)
    cleaned = re.sub(r"μ\s*mol\s*/\s*L", "μmol/L", cleaned)
    cleaned = re.sub(r"\b([A-Za-z])\s*/\s*([A-Za-z])\s*=\s*", r"\1/\2=", cleaned)
    cleaned = re.sub(r"([㐀-鿿]{2,8})\n\n(\d+~\d+)", r"\1\2", cleaned)
    cleaned = re.sub(r"\$\s*([^$\n]{0,80}?(?:℃|\d+(?:\.\d+)?(?:g|mg|kg|ug|μg|ml|mL|L|mm|cm|m|min|s|h|kPa)))\s*\$", r"\1", cleaned)
    cleaned = re.sub(r"\\([A-Za-z]+)\s*\{\s*([^{}\n]{1,160})\s*\}", r"\2", cleaned)
    cleaned = re.sub(r"[ \t]{2,}", " ", cleaned)
    cleaned = re.sub(r"\s+(?=\d+(?:\.\d+)?(?:g|mg|kg|ug|μg|ml|mL|L|mm|cm|m|min|s|h|kPa)\b)", " ", cleaned)
    return cleaned


def _remove_trailing_archive_metadata_artifacts(text: str) -> str:
    return TRAILING_ARCHIVE_METADATA_RE.sub("\n", text)


def _remove_embedded_foreign_math_noise_artifacts(text: str) -> str:
    theorem_re = re.compile(r"Theorem\s+\d+(?:\.\d+)*\.[^\n\r\u3400-\u9fff]{40,1000}")
    markers = ("finite field", "F(x)", "prime ideal", "\\in")

    def replace(match: re.Match[str]) -> str:
        fragment = match.group(0)
        if sum(1 for marker in markers if marker in fragment) >= 2:
            return ""
        return fragment

    cleaned = theorem_re.sub(replace, text)
    cleaned = re.sub(r"\s*\\therefore\s+[A-Za-z]\s*-\s*\d+\s*\\neq\s*\d+\s*;?\s*", " ", cleaned)
    return re.sub(r"\n{4,}", "\n\n\n", cleaned)


def _normalize_temperature_percent_artifacts(text: str) -> str:
    segments = re.split(r"([。！？!?；;\n])", text)
    normalized: list[str] = []
    for segment in segments:
        if not segment or re.fullmatch(r"[。！？!?；;\n]", segment):
            normalized.append(segment)
            continue
        if not re.search(r"(?:体温|发热|高热|高烧|热势)", segment):
            normalized.append(segment)
            continue
        normalized.append(
            re.sub(
                r"(?P<number>\d{2}(?:\.\d+)?)\s*%",
                _temperature_percent_match_to_celsius,
                segment,
            )
        )
    cleaned = "".join(normalized)
    return re.sub(r"(?<=℃)\s*[~～]\s*(?=\d{2}(?:\.\d+)?℃)", "~", cleaned)


def _temperature_percent_match_to_celsius(match: re.Match[str]) -> str:
    value = match.group("number")
    try:
        numeric = float(value)
    except ValueError:
        return match.group(0)
    if 30 <= numeric <= 45:
        before = match.string[max(0, match.start() - 24) : match.start()]
        after = match.string[match.end() : match.end() + 12]
        if re.search(r"(?:占|占比|率|百分比|构成比|有效率|治愈率)\s*$", before):
            return match.group(0)
        if re.search(r"(?:例|病例|人|患儿|患者)\s*[,，、]?\s*占\s*$", before):
            return match.group(0)
        if re.match(r"\s*(?:例|病例|人|患儿|患者|有效|治愈)", after):
            return match.group(0)
        return f"{value}℃"
    return match.group(0)


def _acceptance_blocking_issues(acceptance: dict[str, Any]) -> list[dict[str, Any]]:
    issues: list[dict[str, Any]] = []
    for chunk in acceptance.get("chunks", []):
        if not isinstance(chunk, dict) or chunk.get("accepted") is True:
            continue
        llm_result = chunk.get("llm_result")
        if not isinstance(llm_result, dict):
            continue
        for issue in llm_result.get("blocking_issues", []):
            if isinstance(issue, dict):
                issues.append(issue)
    llm_result = acceptance.get("llm_result")
    if isinstance(llm_result, dict):
        for issue in llm_result.get("blocking_issues", []):
            if isinstance(issue, dict):
                issues.append(issue)
    return issues


def _transcribe_table_flowchart_details(text: str) -> str:
    def replace(match: re.Match[str]) -> str:
        prefix = text[max(0, match.start() - 500) : match.start()]
        if not _near_table_image(prefix):
            return "\n\n"
        rows = _flowchart_rows(match.group("body"))
        if not rows:
            return "\n\n"
        table = ["表格结构转写（由 MinerU flowchart 提取）", "", "| 项目 | 内容 |", "|---|---|"]
        table.extend(f"| {left} | {right} |" for left, right in rows)
        return "\n\n" + "\n".join(table) + "\n\n"

    return MINERU_FLOWCHART_DETAILS_RE.sub(replace, text)


def _near_table_image(prefix: str) -> bool:
    tail = prefix[-500:]
    if re.search(r"!\[[^\]]*(?:表|table)[^\]]*\]\([^)]*\)\s*$", tail, flags=re.IGNORECASE):
        return True
    return bool(re.search(r"(?:^|\n)\s*(?:表|Table)\s*\d+", tail, flags=re.IGNORECASE))


def _flowchart_rows(body: str) -> list[tuple[str, str]]:
    rows: list[tuple[str, str]] = []
    seen: set[tuple[str, str]] = set()
    for raw_line in body.splitlines():
        line = raw_line.strip().strip(";")
        if not line or line.startswith("```") or re.match(r"^(?:flowchart|graph)\b", line, flags=re.IGNORECASE):
            continue
        if "-->" not in line:
            continue
        left_raw, right_raw = line.split("-->", 1)
        left = _flowchart_node_label(left_raw)
        right = _flowchart_node_label(right_raw)
        if not left or not right:
            continue
        row = (left, right)
        if row in seen:
            continue
        seen.add(row)
        rows.append(row)
    return rows


def _flowchart_node_label(raw_value: str) -> str:
    value = raw_value.strip().strip(";")
    bracketed = re.search(r'[\[\(\{]\s*["”]?(.+?)["”]?\s*[\]\)\}]', value)
    if bracketed:
        value = bracketed.group(1)
    else:
        value = re.sub(r"^[A-Za-z0-9_]+\s*", "", value).strip()
        if re.fullmatch(r"[A-Za-z0-9_]+", value):
            return ""
    value = re.sub(r"\s*[-.=]+.*$", "", value).strip()
    value = value.strip("`\"'")
    return value.replace("|", "｜").strip()


def _split_local_structure_glue(text: str, *, structure_labels: tuple[str, ...] | None = None) -> str:
    labels = structure_labels or DEFAULT_STRUCTURE_LABELS
    cleaned = text
    for label in labels:
        escaped = re.escape(label)
        cleaned = re.sub(rf"(?<!^)(?<!\n)(?<=[㐀-鿿A-Za-z0-9）)])\s*({escaped})", r"\n\1", cleaned)
        cleaned = re.sub(rf"({escaped})\s+(?=\S)", r"\1\n", cleaned)
    cleaned = re.sub(r"(?<=年版)(?=(?:[㐀-鿿]{2,4})?《)", "\n", cleaned)
    cleaned = _split_bibliography_glue(cleaned)
    return cleaned


def _split_bibliography_glue(text: str) -> str:
    def replace(match: re.Match[str]) -> str:
        body = match.group("body")
        body = re.sub(r"(\b\d{4})\s+(?=[A-Z])", r"\1\n", body)
        body = re.sub(r"([A-Za-z][A-Za-z ]{2,})\s+(?=\d{4}\b)", r"\1\n", body)
        return f"{match.group('prefix')}{body}"

    return re.sub(r"(?P<prefix>\bReferences:\s*)(?P<body>.+)", replace, text)


def _html_table_tags_to_markdown(text: str) -> str:
    cleaned = re.sub(r"</(?:td|th)>\s*<(?:td|th)[^>]*>", " | ", text, flags=re.IGNORECASE)
    cleaned = re.sub(r"<tr[^>]*>\s*<(?:td|th)[^>]*>", "\n| ", cleaned, flags=re.IGNORECASE)
    cleaned = re.sub(r"</(?:td|th)>\s*</tr>", " |\n", cleaned, flags=re.IGNORECASE)
    cleaned = re.sub(r"</?(?:table|thead|tbody|tfoot)[^>]*>", "\n", cleaned, flags=re.IGNORECASE)
    cleaned = re.sub(r"</?tr[^>]*>", "\n", cleaned, flags=re.IGNORECASE)
    cleaned = re.sub(r"</?(?:td|th)[^>]*>", " | ", cleaned, flags=re.IGNORECASE)
    return cleaned


def _normalize_markdown_tables(lines: list[str], *, table_headers: tuple[tuple[str, ...], ...] | None = None) -> list[str]:
    merged: list[str] = []
    index = 0
    while index < len(lines):
        line = lines[index]
        if _is_table_row(line) and not line.strip().endswith("|"):
            current = line.strip()
            index += 1
            while index < len(lines) and not current.endswith("|"):
                next_line = lines[index].strip()
                index += 1
                if next_line:
                    current = f"{current} {next_line}"
            merged.append(current)
            continue
        merged.append(line)
        index += 1

    merged = _merge_table_continuation_rows(merged, known_headers=table_headers)
    normalized: list[str] = []
    in_table = False
    for index, line in enumerate(merged):
        stripped = line.strip()
        if not stripped:
            previous = normalized[-1].strip() if normalized else ""
            following = _next_nonblank(merged, index + 1)
            if _is_table_row(previous) and _is_table_row(following):
                continue
            in_table = False
            normalized.append(line)
            continue
        if _is_table_row(stripped):
            if not in_table:
                normalized.append(_format_table_row(_table_cells(stripped)))
                following = _next_nonblank(merged, index + 1)
                if _is_table_row(following) and not _is_table_separator(following):
                    normalized.append(_table_separator(stripped))
                in_table = True
                continue
            normalized.append(_format_table_row(_table_cells(stripped)))
            continue
        in_table = False
        normalized.append(line)
    return normalized


def _next_nonblank(lines: list[str], start: int) -> str:
    for line in lines[start:]:
        stripped = line.strip()
        if stripped:
            return stripped
    return ""


def _merge_table_continuation_rows(lines: list[str], *, known_headers: tuple[tuple[str, ...], ...] | None = None) -> list[str]:
    normalized: list[str] = []
    active_cols = 0
    active_header: tuple[str, ...] | None = None
    for line in lines:
        stripped = line.strip()
        if not stripped:
            normalized.append(line)
            continue
        if _is_table_separator(stripped):
            normalized.append(line)
            continue
        if _is_table_row(stripped):
            cells = _table_cells(stripped)
            if not active_cols:
                active_cols = len(cells)
                active_header = tuple(cells)
                normalized.append(_format_table_row(cells))
                continue
            if _is_known_table_header(stripped, known_headers=known_headers):
                active_cols = len(cells)
                active_header = tuple(cells)
                normalized.append(_format_table_row(cells))
                continue
            if active_header and _has_embedded_header(cells, active_header):
                continue
            if len(cells) < active_cols:
                previous = normalized[-1].strip() if normalized else ""
                previous_cells = _table_cells(previous) if previous and _is_table_row(previous) else []
                trailing_empty = _trailing_empty_cell_count(previous_cells)
                if len(previous_cells) == active_cols and trailing_empty >= len(cells):
                    normalized[-1] = _format_table_row(previous_cells[: active_cols - len(cells)] + cells)
                continue
            if len(cells) > active_cols:
                continue
            normalized.append(_format_table_row(cells))
            continue
        active_cols = 0
        active_header = None
        normalized.append(line)
    return normalized


def _has_embedded_header(cells: list[str], active_header: tuple[str, ...]) -> bool:
    if len(cells) < len(active_header):
        return False
    for start in range(1, len(cells) - len(active_header) + 1):
        if tuple(cells[start : start + len(active_header)]) == active_header:
            return True
    return False


def _is_table_row(line: str) -> bool:
    stripped = line.strip()
    return stripped.startswith("|") and stripped.count("|") >= 2


def _is_table_separator(line: str) -> bool:
    stripped = line.strip()
    return bool(re.fullmatch(r"\|?\s*:?-{3,}:?\s*(\|\s*:?-{3,}:?\s*)+\|?", stripped))


def _is_known_table_header(line: str, *, known_headers: tuple[tuple[str, ...], ...] | None = None) -> bool:
    headers = known_headers if known_headers is not None else DEFAULT_TABLE_HEADERS
    return tuple(_table_cells(line)) in headers


def _has_embedded_table_header(cells: list[str], *, known_headers: tuple[tuple[str, ...], ...] | None = None) -> bool:
    headers = known_headers if known_headers is not None else DEFAULT_TABLE_HEADERS
    for header in headers:
        header_len = len(header)
        for start in range(1, len(cells) - header_len + 1):
            if tuple(cells[start : start + header_len]) == header:
                return True
    return False


def _table_cells(line: str) -> list[str]:
    return [cell.strip() for cell in line.strip().strip("|").split("|")]


def _format_table_row(cells: list[str]) -> str:
    return "| " + " | ".join(cells) + " |"


def _trailing_empty_cell_count(cells: list[str]) -> int:
    count = 0
    for cell in reversed(cells):
        if cell:
            break
        count += 1
    return count


def _table_separator(header: str) -> str:
    cell_count = max(1, len(header.strip().strip("|").split("|")))
    return "|" + "|".join("---" for _ in range(cell_count)) + "|"


def _text_sha256(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def _merge_soft_wrapped_lines(lines: list[str], *, structure_labels: tuple[str, ...] | None = None) -> list[str]:
    result: list[str] = []
    for line in lines:
        stripped = line.strip()
        if not stripped and result and not result[-1].strip():
            continue
        if (
            len(result) >= 2
            and not result[-1].strip()
            and stripped
            and (
                _looks_like_blank_separated_word_split(result[-2].strip(), stripped)
                or _looks_like_blank_separated_formula_fragment(result[-2].strip(), stripped)
                or _looks_like_blank_separated_forced_break(
                    result[-2].strip(),
                    stripped,
                    structure_labels=structure_labels,
                )
            )
        ):
            result[-2] = result[-2].rstrip() + stripped
            continue
        if result and stripped and _looks_like_forced_break(result[-1].strip(), stripped, structure_labels=structure_labels):
            result[-1] = result[-1].rstrip() + stripped
        else:
            result.append(line)
    return result


def _looks_like_blank_separated_word_split(previous: str, current: str) -> bool:
    if not previous or not current:
        return False
    known_splits = (
        ("手", "术"),
        ("治", "疗"),
        ("检", "查"),
        ("诊", "断"),
    )
    return any(previous.endswith(left) and current.startswith(right) for left, right in known_splits)


def _normalize_chronology_list_lines(lines: list[str]) -> list[str]:
    return [f"- {line.strip()}" if _looks_like_chronology_range_line(line) else line for line in lines]


def _looks_like_chronology_range_line(value: str) -> bool:
    stripped = value.strip()
    if not stripped or stripped.startswith(("#", "|", "-", "*", "+", "![")):
        return False
    return bool(
        re.match(
            r"^(?:1[89]\d{2}|20\d{2})\s*[～~—-]\s*(?:1[89]\d{2}|20\d{2})\s*年",
            stripped,
        )
    )


def _looks_like_blank_separated_forced_break(
    previous: str,
    current: str,
    *,
    structure_labels: tuple[str, ...] | None = None,
) -> bool:
    if _looks_like_case_heading_line(previous):
        return False
    if _looks_like_front_matter_line(previous) or _looks_like_front_matter_line(current):
        return False
    return _looks_like_forced_break(previous, current, structure_labels=structure_labels)


def _looks_like_blank_separated_formula_fragment(previous: str, current: str) -> bool:
    if not previous or not current:
        return False
    if _looks_like_case_heading_line(previous) or _looks_like_front_matter_line(previous):
        return False
    dosage = r"\d+(?:\.\d+)?\s*(?:g|克|kg|mg|ml|mL|帖|付|枚|片|丸|粒|钱|分)"
    if len(current) > 240:
        return False
    if len(current) > 48 and not re.match(dosage, current, flags=re.IGNORECASE):
        return False
    if not re.search(dosage, previous, flags=re.IGNORECASE):
        return False
    if not re.search(dosage, current, flags=re.IGNORECASE):
        return False
    return bool(re.search(r"[㐀-鿿A-Za-z0-9]$", previous) and re.search(r"^[㐀-鿿A-Za-z0-9]", current))


def _looks_like_case_heading_line(value: str) -> bool:
    return bool(re.match(r"^(?:案|例)\s*[一二三四五六七八九十百千〇零两\d]+(?:\s|[：:]|[㐀-鿿A-Za-z])", value.strip()))


def _looks_like_front_matter_line(value: str) -> bool:
    return bool(
        re.match(
            r"^(?:主编|编委|审定|编著|整理|作者|发行者|出版者|印刷者|经销者|邮政编码|传真|定价|书号|开本|ISBN|网址|社长热线|读者服务部电话|购书热线|官方微博|淘宝天猫网址|上架建议|中国版本图书馆|图书在版编目)",
            value.strip(),
        )
    )


def _looks_like_forced_break(previous: str, current: str, *, structure_labels: tuple[str, ...] | None = None) -> bool:
    labels = structure_labels or DEFAULT_STRUCTURE_LABELS
    if not previous or not current:
        return False
    if previous.startswith("#") or current.startswith("#"):
        return False
    if current.startswith(labels):
        if not re.search(r"[头面项颈肩背胸腹腰肘腕手髀髋膝踝足]$", previous):
            return False
    if previous.endswith("年版"):
        return False
    if re.match(r"^([一二三四五六七八九十]+、|\d+[.、])", current):
        return False
    return _looks_like_general_paragraph_fragment(previous, current)


def _looks_like_general_paragraph_fragment(previous: str, current: str) -> bool:
    if len(previous) < 8:
        return False
    if previous.startswith(("#", "|")) or current.startswith(("#", "|")):
        return False
    if current.startswith(("- ", "* ", "+ ")) or re.match(r"^\d+[.)、]\s*", current):
        return False
    if previous.endswith(("。", "！", "？", ".", "!", "?", "：", ":", "；", ";", '"', "'", "』", "】", ")", "）", "`")):
        return False
    if _looks_like_cjk_numbered_list_line(previous) and _looks_like_cjk_numbered_list_line(current):
        return False
    if len(current) < 8:
        if (
            len(previous) >= 18
            and re.search(r"[㐀-鿿]$", previous)
            and re.fullmatch(r"[㐀-鿿]{1,7}[，,。；;：:、]?", current)
        ):
            return True
        return False
    cjk_boundary = bool(re.search(r"[㐀-鿿]$", previous) and re.search(r"^[㐀-鿿]", current))
    comma_boundary = previous.endswith(("，", ",", "、"))
    if comma_boundary and _looks_like_short_cjk_verse_line(previous) and _looks_like_short_cjk_verse_line(current):
        return False
    if not cjk_boundary and not comma_boundary and len(previous) + len(current) < 80:
        return False
    return bool(re.search(r"[㐀-鿿A-Za-z0-9，,、]$", previous) and re.search(r"^[㐀-鿿A-Za-z0-9]", current))


def _looks_like_short_cjk_verse_line(value: str) -> bool:
    if len(value) > 28:
        return False
    if re.search(r"[A-Za-z0-9]", value):
        return False
    return bool(re.fullmatch(r"[㐀-鿿，、。！？；：""''（）《》〈〉·]+", value))


def _looks_like_cjk_numbered_list_line(value: str) -> bool:
    return bool(re.match(r"^[一二三四五六七八九十百千〇零两]+、\S+", value))
